export { default as IconHeart } from './IconHeart.vue'
export { default as IconStar } from './IconStar.vue'
export { default as IconVector } from './IconVector.vue'
export * from './shopping'
export * from './basic'
