export { default as IconHeart } from './IconHeart.vue'
export { default as IconHome } from './IconHome.vue'
export { default as IconPencil } from './IconPencil.vue'
export { default as IconStar } from './IconStar.vue'
export { default as IconTrash } from './IconTrash.vue'
export { default as IconVector } from './IconVector.vue'
